version: '3'
services:
  server:
    build: ./server
    ports:
     - "5000:5000"
    networks:
     - my-network
  client:
    build: ./client
    ports:
     - "5000:5000"
    networks:
     - my-network
networks:
  my-network:
